worker_processes 2;

events {
    worker_connections 8192;
    multi_accept on;
}

http {
    access_log off;
    error_log /dev/stderr warn;

    keepalive_timeout 30s;
    keepalive_requests 10000;
    sendfile off;
    tcp_nopush off;
    tcp_nodelay on;

    upstream api {
        server api1:8080 max_fails=0;
        server api2:8080 max_fails=0;
    }

    server {
        listen 9999 backlog=8192 reuseport;

        location / {
            proxy_pass http://api;

            # A API C é bloqueante e fecha uma conexão por request.
            # Não usar keepalive no upstream.
            proxy_http_version 1.0;
            proxy_set_header Connection close;

            proxy_connect_timeout 2s;
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;

            # Para payload pequeno, buffering ON é mais estável e barato.
            proxy_request_buffering on;
            proxy_buffering on;
            proxy_buffers 4 4k;
            proxy_busy_buffers_size 8k;

            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            proxy_next_upstream_tries 2;
        }
    }
}
